server:
  port: 8082

#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 124.221.233.62:8848
#      username: nacos
#      password: nacos

jwt:
  secret: qzkqzkqzkqzkqzkqzkqzkqzkqzkqzkqzkqzkqzkqzkqzkqzkqzk   # 密码
  expire-time-in-second: 1209600        # 单位/秒 两周